name: alfx
title: alfx
description: awsl
tags:
  - graphcis
  - blog
  - template
  - jekyll
  - theme
  - netlify
show_hero: false

menu:
  - title: 游戏
    url: /category/Project/
  - title: 文章
    url: /category/tech/
  - title: 画廊
    url: /gallery/
  - title: 关于我
    url: /about
  # - title: 杂物
  #   url: /category/other/
email: 906130960@qq.com

