name: alfx
title: alfx
description: awsl
tags:
  - graphcis
  - blog
  - template
  - jekyll
  - theme
  - netlify
show_hero: false

menu:
  - title: Nier:9
    url: /Nier9/
  - title: 无尽世界/Endless World
    url: /EndlessWorld/
  - title: 我们仍未知道那天是谁拿走了钥匙
    url: /Nier9/
  - title: 杯面之神
    url: /CupNoodleKami/
  - title: GALLERY
    url: /gallery/
  - title: 关于我
    url: /about
  # - title: 杂物
  #   url: /category/other/
email: 906130960@qq.com

