name: Llapuras
title: Llapuras
description: Diegofornalha
tags:
  - blog
  - template
  - jekyll
  - theme
  - netlify
show_hero: false

menu:
  - title: 主页
    url: /
  - title: 文章
    url: /category/article/
  - title: 游戏
    url: /category/project/
  - title: 艺术
    url: /category/art/
  - title: 代码
    url: /category/tech/
  - title: 杂
    url: /category/other/
  - title: 关于我
    url: /about
email: 906130960@qq.com