name: Llapuras
title: Llapuras
description: awsl
tags:
  - graphcis
  - blog
  - template
  - jekyll
  - theme
  - netlify
show_hero: false

menu:
  # - title: 文
  #   url: /category/article/
  - title: GAME
    url: /category/project/
  - title: DRAW
    url: /category/art/
  - title: TECH
    url: /category/tech/
  - title: 0v0
    url: /category/other/
  - title: 关于我
    url: /about
email: 906130960@qq.com