name: alfx
title: alfx
description: awsl
tags:
  - graphcis
  - blog
  - template
  - jekyll
  - theme
  - netlify
show_hero: false

menu:
  - title: Nier9
    url: /Nier9/
  - title: 那一天，场面一度十分混乱
    url: /Nier9/
  - title: Endless World
    url: /Nier9/
  - title: GALLERY
    url: /gallery/
  # - title: 杂物
  #   url: /category/other/
  - title: 关于我
    url: /about
email: 906130960@qq.com

