name: Llapuras
title: Llapuras
description: awsl
tags:
  - graphcis
  - blog
  - template
  - jekyll
  - theme
  - netlify
show_hero: false

menu:
  - title: 文
    url: /category/article/
  - title: 戏
    url: /category/project/
  - title: 绘
    url: /category/art/
  - title: 码
    url: /category/tech/
  - title: 杂
    url: /category/other/
  - title: 关于我
    url: /about
email: 906130960@qq.com